services:
  fcp-dal-api:
    image: fcp-dal-api
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      ALL_SCHEMA_ON: true
      EVENT_HUB_DISABLED: true
      LOG_LEVEL: http
      NODE_ENV: development
      PORT: 3000
      RURAL_PAYMENTS_PORTAL_API_URL: http://fcp-dal-upstream-mock:3100/rpp/
      SOC_APPPLICATION_IDENTIFIER: DAL001
    networks:
      - cdp-tenant

################################################################################

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
